### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_UI#10]
Посмотреть внимательнее css аналогично замечанию в первом проекте, так как зашел, а там не все так хорошо, как могло бы быть.

**Comment by arkhannanov** [comment]
Да, да я просто еще не успел.

**Comment by arkhannanov** [comment]
Готово. Только не везде все получилось. В ишью #11 я описал возникшие трудности. Просьба прокомментировать.

**Comment by Sergio-Ka** [comment]
Зачем внутри src опять папка scss с каким-то одним файликом? Зачем опять там же какая-то папка js с двумя файликами? Если какая-то сторонняя библиотека и её нет в npm, то ее ложить в папку vendors в корне проекта, в ней самой ничего не править. Все подключаемые файлы подключать в точке входа (касательно второго js файла).

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Сделано в рамках аналогичного ишью Егора.

**Comment by arkhannanov** [comment]
3. Готов в рамках ишью от Егора.

#12

**Comment by arkhannanov** [comment]
4. 

> Зачем-то еще один повторяющийся блок ripple (описание класса css), правда уже в другом файле header-rent-auto.scss. Для чего решительно не ясно.

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
5. 

> Ссылка на родителя через амперсанд

Исправлено в раках ишью #12

**Comment by arkhannanov** [comment]
6. 

> Еще один повторяющийся блок ripple (описание класса css), в третьем файле messaging.scss.

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
7. 

> Ссылка на родителя через амперсанд

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
8.

> Там же четвертый повторяющийся блок ripple

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
9.

> файл page.scss жуткий бардак. Описания правил для блоков - это часть реализации самих блоков и должно находится с правилами для них. Позиционирование на блоках - то есть внешнее поведение, сплошные марджины, ширины. В первом проекте вроде об этом долго рассказывалось.

Причесал все pages в рамках ишью #12. Так нормально? Или нужно подгонять именно само поведение блоков изначально при создании. Поясни плиз.

**Comment by arkhannanov** [comment]
10. 

> Там же всякая такая ерунда .btn. Про именование говорилось уже тоже не мало.

Исправлены сокращения btn и prev

**Comment by arkhannanov** [comment]
11. 

> последние два относятся ко ВСЕМ МЕСТАМ КОТОРЫЕ НАЧИНАЮТСЯ С page- .Там еще и именования русскими словами, типа .drop-down-korobka

Готово. Избавился от русских наименований английскими буквами.

**Comment by arkhannanov** [comment]
12. 

> Ссылка на родителя через амперсанд

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
13.

> Блок внутри блока

Исправлено.

**Comment by arkhannanov** [comment]
14. 

> Ссылка на родителя через амперсанд

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
15. 

> там же пятый блок ripple

Исправлено в рамказ ишью #12

**Comment by arkhannanov** [comment]
16. 

> ссылка на родителя через амперсанд

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
17.

> Что мешает инпут добавить css класс и вешать правила на него и не нарушать БЭМ?

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
18.

Исправлено в рамках ишью #12

**Comment by arkhannanov** [comment]
19. 

> Очень много css правил. При таком их количестве возникает вопрос в том все ли там нормально сделано, нет ли там дублирующихся правил и так далее. Скорее всего есть. Судя по начальному ответу по ишью - все сделано уже с учетом замечаний первого проекта, по факту - приходится сидеть, делать работу по рефакторингу за автора и тыкать в каждое место, хотя замечания типовые.

Тут имеется ввиду что css правиль вообще на проекте много или в каком-то компоненте?

**Comment by Sergio-Ka** [comment]
1. На классы с префиксами js- никакие свойства не вешаются, они нужны для того только, чтобы работать с ними в js. Свойства вешаются на классы без префикса. Сами по себе классы с префиксом быть не должны. Они должны быть только миксами к такми же классам но без префикса.
  .js-calendar {

    &__item {
      padding: 0;
      color: #1e2633;
      font-weight: lighter;
      line-height: 1.2;
      text-align: center;
      border: 0;
**Это ко всему проекту относится.**
2. Внешнее поведение на блоках. **Посмотреть во всем проекте.**
.events {

  width: 11.875rem;
  height: 8.833rem;
  display: flex;
  flex-direction: row;
  margin: 1rem 0.5rem 1.9rem 0;
3. Что такое tel?
  &__tel {
    font-size: 1rem;
  }
4. Едва ли в английском языке есть слово upperheader. Как вариант upper-header.
&-upperheader {
5. Что такое col? Гуглопереводчик говорит, что это переводится как седло.
&-table-col-header {
        padding: 0 0;
6. Что такое logout-href? Может быть logout-link?
  &__logout {
    font-size: 0.517rem;
    font-weight: bold;
    color: white;
    line-height: 1.292rem;
    margin-top: 0.2rem;

    &-href {
7. Какую роль здесь играют буквы js? Если это префикс, то он вешается на полное имя класса, если это означает что форма работает на js, то тоже странно.
 &__js-form-rent-auto-completeform {
    color: red;
    font-size: 1rem;
    white-space: nowrap;
    margin-left: 0.9rem;
  }

  &__js-form-rent-auto-submit {
    position: absolute;
    top: 2rem;
    margin-left: 1.8rem;
  }
8. Что такое svg? Как вариант image. В блоке pie аналогично.
.percents {

  position: relative;

  &__svg {
    width: 4rem;
    height: 4rem;
  }
9. Зачем в папке pages в каждом стилевом файле дублируются одни и те же css правила для html и body?

**Comment by arkhannanov** [comment]
1. Исправлно.

**Comment by arkhannanov** [comment]
2. Исправлено в рамках ишью #14

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
> 3. Что такое tel?

Исправлено.

**Comment by arkhannanov** [comment]
5. Что такое col? Гуглопереводчик говорит, что это переводится как седло.

**Comment by arkhannanov** [comment]
> 7. Какую роль здесь играют буквы js? Если это префикс, то он вешается на полное имя класса, если это означает что форма работает на js, то тоже странно.

Исправлено.

**Comment by arkhannanov** [comment]
9. Зачем в папке pages в каждом стилевом файле дублируются одни и те же css правила для html и body?

Исправлено.
