### ISSUE TITLE
Трудности на проекте

### ISSUE THREAD

**Issue by arkhannanov** [arkhannanov/FSD_UI#11]
1. calendar.scss

.patch {
  width: 11.617rem;
  height: 1.125rem;
  background: #e75735;
  margin-top: -1.083rem;
  margin-left: -0.071rem;
  position: relative;
  z-index: -300;
}

.footer {
  width: 10.825rem;
  height: 1.25rem;
  background-color: #e5e5e5;
  font-weight: normal;
  margin-left: -0.071rem;
  font-size: 0.542rem;
  letter-spacing: 0.027rem;
  color: #868686;
  text-align: left;
  padding-left: 0.792rem;
  padding-top: 0.792rem;
  margin-bottom: 1.458rem;
}

Не понятно как обойтись без отрицательных марджинов, нужно чтобы элемент patch наезжал на верхний элемент, перекрывал его. Плюс при добавлении элемент patch  и footer JS элементы немного смещены вправо. Чтобы из выровнять приходится использовать отрицательные марджины.

**Comment by arkhannanov** [comment]
2. drop-down.scss

Не получается сделать короткую запись background:
&__btn {
....
background-image: #4eb7a8 url('./images/drop-down.png') 0.333rem 0.375rem no-repeat;
....
}

Редактор подчеркивает красным.

**Comment by arkhannanov** [comment]
3. form-gamma.scss

&__message-text {
    width: 10.417rem;
    height: 3.75rem;
    background: #e5e5e5;
    margin-top: -2rem;
  }

Тут тоже непонятно как поднять элемент без отрицательного марджина.

**Comment by arkhannanov** [comment]
4. header-alfa.scss

&-button {
      width: 1rem;
      height: 1rem;
      border: 0;
      border-radius: 0.125rem;
      position: relative;
      background: #e75735 url('./images/search-icon.png') 0.271rem 0.2rem no-repeat;
      font-size: 0.333rem;
      margin-left: -1rem;
    }

Тоже непонятно как сделать чтобы кнопка наезжала на input без отрицательных марджинов.

**Comment by arkhannanov** [comment]
5. messaging.scss

&__avatar-container {
    height: 3.917rem;
    width: 3.9017rem;
    background: #e5e5e5;
    border-radius: 50%;
    margin-left: 4.042rem;
    margin-top: -1.958rem;
  }

Тут тоже непонятно как обойтись без отрицательного маржина, если элемент нужно наложить на верхний.

**Comment by arkhannanov** [comment]
6. page-sigma.scss

&__button {
      color: white;
      border: none;
      cursor: pointer;
      width: 1.292rem;
      height: 1.167rem;
      margin-left: 9.167rem;
      top: -1.167rem;
      position: relative;
      border-radius: 0.125rem;
      background: #4eb7a8 url('./images/drop-down.png') 0.333rem 0.375rem no-repeat;
    }

Без top не получается загнать кнопку в нужное место.

**Comment by arkhannanov** [comment]
5. slider.scss

.slider__rs-label {
  position: relative;
  transform-origin: center center;
  display: block;
  width: 1.458rem;
  height: 1.167rem;
  background: url('./images/slider-bubble-bg.png') no-repeat;
  text-align: center;
  left: 3.917rem;
  padding-top: -1.25rem;
  box-sizing: border-box;
  color: white;
  font-size: 0.542rem;
  font-weight: 400;
  line-height: 1.167rem;
  letter-spacing: 0.027rem;
  margin-bottom: -0.3rem;
  margin-left: -0.11rem;
}

Непонятно как точно спозиционировать лейбл над слайдером без отрицательных марджинов.

**Comment by arkhannanov** [comment]
6. stages.scss

&__circles-wrapper {
    display: flex;
    flex-direction:row;
    justify-content:space-between;
    width: 25.208rem;
    margin-top: -0.708rem;

    #stages__first-circle,
    #stages__second-circle,
    #stages__third-circle,
    #stages__fourth-circle,
    #stages__fifth-circle {
      width: 1.208rem;
      height: 1.208rem;
      border-radius: 50%;
      background: #e5e5e5;
      border: 0;
      font-family: $mainFont;
      font-size: 0.583rem;
      line-height: 1.25rem;
      letter-spacing: 0.029rem;
      color: #ffffff;
    }

Непонятно как круги наложить на верхние элементы без отрицательных маржинов.

**Comment by arkhannanov** [comment]
7. step-slider.scss

#step-slider_color {
  margin-top: -0.45rem;
  margin-left: 0.083rem;
  width: 7.583rem;
  height: 0.208rem;
  position: relative;
  background: #4eb7a8;
  z-index: 100;
  border-radius: 0.083rem;
}

Тут тоже непонятно как полоску с цветом реализовать без отрицательного марджина.

**Comment by Sergio-Ka** [comment]
Тут я так понимаю, ты хочешь чтобы мы за тебя решили проблемы возникшие? Я вот тебе со всей ответственностью могу сказать, что можно делать без отрицательных марджинов, если без них не получается, то значит компонент спроектирован не правильно. Например когда блоки div навроде твоего patch вставляются не в ячейку таблицы, а просто бросаются между строками в теле таблицы. Про то как оформлять блоки по БЭМ (типа patch, footer) я и так уже писал неоднократно. Про то, что нельзя вешать свойства на селектор тега я тоже писал уже.
![image](https://user-images.githubusercontent.com/33621369/60716366-67896f80-9f49-11e9-97c9-5ed609607d18.png)
Тут вообще не понятно кстати на кой черт надо было городить свой календарь, если в jQuery UI есть календарь и так? Тем более что как здесь сделано. К чему генерация тела календаря внутри js?
На счет конкретно позиционирования - такие вещи всякими обертками решаются с отступами, как вариант (который хуже) - абсолютное позиционирование. В общем читай материал, спрашивай у людей в чате, когда формализуешь задачу для себя, а нет так что вот ничего не получается, напишу дяденькам, сложу ручки сяду и буду сидеть ждать, когда они за меня сделают.

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Готово.

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
5. Готово. Уже не актуально.

**Comment by arkhannanov** [comment]
6. Готово.
