### ISSUE TITLE
инлайн стили

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#12]
```pug
button.button__item(name="button", style=`width: ${width}; height: ${height}; font-size:${fontSize}; border: 0.042rem solid ${color}; box-shadow: 0 -0.083rem ${color} inset; color: ${color};`, onmouseover=`this.style.backgroundColor ='${color}'; this.style.color ='#ffffff'`, onmouseout=`this.style.backgroundColor='#ffffff'; this.style.color ='${color}' `)= name
```

не много ли здесь инлайн стилей? мб лучше стоит сделать модификаторы?

**Comment by arkhannanov** [comment]
C модификаторами то любой стиль не задашь, любой размер, любой цвет и так далее.

**Comment by Frolikow** [comment]
По размерам спорно, можно сделать модификаторы для начального блока с кнопками, будет например small/big с фиксированными размерами, и можно сделать модификатор custom с размерами 100% и размеры кнопки задавать через родительский блок. Размер шрифта тоже легко вынести в модификаторы, ну все что с цветом - тоже в модификаторы. 
Если можно сделать модификаторами - надо делать модификаторами. Единственное исключение - это если модификатор ооочень сильно усложняет какой-то простой элемент.
А инлайн стили это всегда крайность, которую следует избегать

**Comment by Sergio-Ka** [comment]
Вопрос здесь в том, что слишком большая универсальность - это такая же крайность как и ее отсутствие. Всего не предусмотришь. У тебя здесь фактически все возможные варианты отображения кнопок есть на макете, большего не требуется, а стало быть и правда можно модификаторами обойтись. Риппл эффект должен вешаться не на все кнопки, а стало быть тоже скорее всего это модификатор должен быть. Кроме того сейчас там у тебя риппл это по факту блок, который добавляется, но не убирается. Сто раз кликнул - 100 блоков добавилось. Посмотри в инспекторе. Надо вешать удаление по таймеру.

**Comment by arkhannanov** [comment]
Все готово!

**Comment by Frolikow** [comment]
https://github.com/arkhannanov/FSD_UI/blob/943974d4870d03a6c7caa809e496c05077dd4263/src/blocks/button/button.pug#L3-L4

так не пойдет. что у тебя за класс на элементе получается? даже нет, что у тебя за сдвоенный модификатор без элемента? 

По БЭМу:
1) Модификатор не может существовать сам по себе. Обязательно должен быть блок/элемент который модифицируется модификатором. 
2) Модификаторы, должны быть 
+ булевыми, т.е. либо что-то есть, либо нет. Например: `button /  button_disabled`
+ ключ-значение, т.е. если модификатор предполагает различные варианты. Например: `button_color_red / button_color_green`

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
Ну и стили сразу поправляй) зачем писать стили для `&__item_color_green`?
Ты ведь умеешь ссылаться на верхние уровни) не нужно повторять имя элемента и модификатора

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/61024666-8455f500-a3d8-11e9-9e66-bf307f570ddb.png)

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
В стилях следует писать начиная с блока, ты зря удалил. Щас у тебя стили начинаются с элемента.
```sass
.button
  &__item
    &_color
.......
    &_size
.......
```
блок всегда записывай, даже если для него нету стилей. Это надо для наглядности и так будет общий стиль, потому что в большинстве случаев для блока стиля есть

**Comment by arkhannanov** [comment]
Готово, в том числе и для стрелок.

**Comment by Frolikow** [comment]
подобные места еще подправь
![image](https://user-images.githubusercontent.com/25764783/61186888-dc208480-a694-11e9-9890-9e7619cda404.png)
зачем два раза `green` писать

**Comment by arkhannanov** [comment]
`подобные места еще подправь
image
зачем два раза green писать`

Это же _green и _green: hover

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/61236598-8fa37a80-a762-11e9-84c7-624cd53140e8.png)

**Comment by arkhannanov** [comment]
:hover теперь вложены

**Comment by Frolikow** [comment]
+ вот тут наведи тоже порядок, у тебя уже есть стили для направлений, скомпонуй все логично
![image](https://user-images.githubusercontent.com/25764783/61317052-69e2a800-a82c-11e9-846a-5740caa1ea3f.png)
+ здесь пропустил оформление вложенности
![image](https://user-images.githubusercontent.com/25764783/61317434-276d9b00-a82d-11e9-9001-1d93a4cf9a37.png)
+ здесь я не понял, почему в одном месте ты используешь короткую запись, а рядом пишешь весь класс целиком?:/
![image](https://user-images.githubusercontent.com/25764783/61317499-4a984a80-a82d-11e9-96d8-98597ac78595.png)
 + мне кажется `.ripple` имеет смысл сделать элементом блок button

+ в блоке `events` у тебя что, стили для кнопки заново написаны? это абсолютно недопустимо в задании, которое подразумевает обучение компонентной верстке. у тебя уже есть компонент кнопки, просто подкючай его где нужно и все) если не подходит по размерам или цвету, то продумывай дополнительные модификаторы

+ и в блоке form опять кнопка самодельная

+ и в блоке messaging опять кнопка самодельная

+ и на твоих кастомных страницах почему кнопки прописаны руками? используй готовый компонент

+ блок user. оформелние вложенности
![image](https://user-images.githubusercontent.com/25764783/61319130-c647c680-a830-11e9-8a71-6fa52db57f65.png)

+ блок toggle. оформление вложенности
![image](https://user-images.githubusercontent.com/25764783/61319158-da8bc380-a830-11e9-994c-f1fe02b43150.png)

+ блок tick-boxes. зачем селектор по атрибуту? через классы не работает? и зачем отступ  в две строки?
![image](https://user-images.githubusercontent.com/25764783/61319214-f42d0b00-a830-11e9-93ea-67e06fa28697.png)
удаляй лишние комментарии
![image](https://user-images.githubusercontent.com/25764783/61319308-2b032100-a831-11e9-8613-f77fba535a7c.png)

+ блок stages. что это за класс такой? 
селекторы по тегу запрещены, но это не значит что имя тега нужно использовать в классе. придумай логичное имя для элемента
![image](https://user-images.githubusercontent.com/25764783/61319406-643b9100-a831-11e9-8e36-1656d5bfcaaa.png)
иименование с перечислением. серьезно? опять? это во-первых. во-вторых, если я захочу чтоб у меня треугольники были? мне все классы везде переписывать? надо придумать универсальное название
![image](https://user-images.githubusercontent.com/25764783/61319527-98af4d00-a831-11e9-9423-8a5ba4737f29.png)

+ блок page. тут вообще перебор. у тебя есть конкретный блок, **page**. **ЗАчем 21 блок** внутри блока page??? и элементы от этих блоков там же..и модификаторы не понятные. модификатор не может существовать сам по себе. 

___
p.s. я подумал, мб мы тебя загружаем сильно задачами что ты не успеваешь **внимательно** все исправлять и обдумывать то, что мы тебе задаем? я попробую пореже смотреть, чтобы ты не торопился и аккуратно все делал, на совесть.

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Готово.

**Comment by arkhannanov** [comment]
`мне кажется .ripple имеет смысл сделать элементом блок button`

4. Готово.

**Comment by arkhannanov** [comment]
`в блоке events у тебя что, стили для кнопки заново написаны? это абсолютно недопустимо в задании, которое подразумевает обучение компонентной верстке. у тебя уже есть компонент кнопки, просто подкючай его где нужно и все) если не подходит по размерам или цвету, то продумывай дополнительные модификаторы`

5. Готово.

**Comment by arkhannanov** [comment]
`и в блоке form опять кнопка самодельная`
6. Готово.

**Comment by arkhannanov** [comment]
`и в блоке messaging опять кнопка самодельная`
7. Готово

**Comment by arkhannanov** [comment]
> и на твоих кастомных страницах почему кнопки прописаны руками? используй готовый компонент

8. Готово

**Comment by arkhannanov** [comment]
> блок user. оформелние вложенности

Непонятно как оформить вложенность, так как стили задаются внутри &:hover, то есть если ставить & то будет приписываться &:hover.

**Comment by arkhannanov** [comment]
> блок toggle. оформление вложенности

10. Готово.

**Comment by arkhannanov** [comment]
> блок tick-boxes. зачем селектор по атрибуту? через классы не работает? и зачем отступ в две строки?

> удаляй лишние комментарии

11. Готово.

**Comment by arkhannanov** [comment]
>  блок page. тут вообще перебор. у тебя есть конкретный блок, page. ЗАчем 21 блок внутри блока page??? и элементы от этих блоков там же..и модификаторы не понятные. модификатор не может существовать сам по себе.

13. Готово, теперь не блоки, теперь элементы блока. Модификаторов нет.

**Comment by Frolikow** [comment]
В целом, гораздо лучше стало

> > блок user. оформелние вложенности
> 
> 1. Не готово.
> 
> Непонятно как оформить вложенность, так как стили задаются внутри &:hover, то есть если ставить & то будет приписываться &:hover.

![image](https://user-images.githubusercontent.com/25764783/61588092-816cb880-abbf-11e9-9b77-6ebf567c4d70.png)

**Comment by arkhannanov** [comment]
> блок user. оформелние вложенности

Готово.
