### ISSUE TITLE
блок drop-down

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#13]
Следует убрать хардкод. Сейчас у тебя список строго под 3 пункта. Перепиши чтобы циклом перебирать входящие данные и отрисовывать исходя из данных

**Comment by Frolikow** [comment]
> Следует убрать хардкод. Сейчас у тебя список строго под 3 пункта. Перепиши чтобы циклом перебирать входящие данные и отрисовывать исходя из данных

**Comment by Frolikow** [comment]
Выпадающий список имеет конкретный внешний вид. В psd макете в слоях можно посмотреть как должны выглядеть пункты списка

**Comment by Frolikow** [comment]
На макете переход перед кнопкой иначе выглядит
![image](https://user-images.githubusercontent.com/25764783/61024515-10b3e800-a3d8-11e9-9bd0-cc82dbff2ed0.png)

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
на блоке поиска такая же проблема

**Comment by arkhannanov** [comment]
Готово.
