### ISSUE TITLE
Опять замечания по БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_UI#14]
С бэм на проекте очень все плохо:
-используются селекторы тэгов
-используются селекторы id
-используются блоки внутри компонентов, которые таковыми не являются по сути и которые не оформлены как блоки
-нарушена нотация именования типа calendar__btn_prev

**Comment by Sergio-Ka** [comment]
Тут еще кстати замечание. Обычно то, что у тебя сейчас вынесено в pages предполагает использование механизма шаблонов, то есть типа то что с extends block делается. То есть один файл в котором поаторяющиеся вещи (типа footer, header, меню например) и отдельные файлы страниц на которых уже лежит по блокам то что подключается (как правило лежать миксины). Как сейчас сделаны миксины страниц, которые тупо подключаются не очень. Структура страниц по хорошему должна быть в pages, а в ней миксинами подключаются не сами страницы, а используымые компоненты.

**Comment by arkhannanov** [comment]
1. Не понял что неправильно в наименовании calendar__btn_prev?

**Comment by arkhannanov** [comment]
`-используются блоки внутри компонентов, которые таковыми не являются по сути и которые не оформлены как блоки`

Просьба показать где это так.

**Comment by arkhannanov** [comment]
Вроде все готово!

**Comment by arkhannanov** [comment]
`Тут еще кстати замечание. Обычно то, что у тебя сейчас вынесено в pages предполагает использование механизма шаблонов, то есть типа то что с extends block делается. То есть один файл в котором поаторяющиеся вещи (типа footer, header, меню например) и отдельные файлы страниц на которых уже лежит по блокам то что подключается (как правило лежать миксины). Как сейчас сделаны миксины страниц, которые тупо подключаются не очень. Структура страниц по хорошему должна быть в pages, а в ней миксинами подключаются не сами страницы, а используымые компоненты.`

Вот этот блок не понял немного. Просьба написать поподробнее.

**Comment by Frolikow** [comment]
Добавлю по БЭМу. Прилично мест, где не понятно образование и необходимость классов. Например в блоке календаря вообще мешанина. 
```pug
mixin calendar
    .calendar__wrapper
        .page-calendar.calendar
            .calendar__upperheader
                span.calendar__day
            .calendar__header
                span.calendar__month
                button.calendar__btn.calendar__btn-prev
                button.calendar__btn.calendar__btn-next
            .calendar__patch

```
что не так: 
+ у миксина есть имя конкретное, оно должно точно совпадать с блоком который в этом миксине
+ сейчас у тебя миксин возвращает элемент(что нельзя) а уже потом в элементе "блок"
+ двойной блок? по стандартам примеси нельзя использовать
+ `calendar__btn-prev`, на мой взгляд тоже не очень выглядит этот класс. старайся не использовать сокращения, они могут быть не понятны другому человеку который подключиться к твоему проекту.  
+ сейчас у тебя `button.calendar__btn.calendar__btn-next` - два элемента в одном. значит это примесь, примеси использовать нельзя

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/61025677-a00eca80-a3db-11e9-9736-5ab234c53c2c.png)
вот еще пример неудачного именования. модификатор сам по себе не может существовать, он должен что-то модифицировать. 
Хоть здесь и видно что просто пропустил одно подчеркивание, будь внимательнее. из-за таких мелочей иногда очень долго приходиться дебажить

**Comment by arkhannanov** [comment]
C Календарем готово.

**Comment by arkhannanov** [comment]
Messaging тоже исправлено.

**Comment by Frolikow** [comment]
Здесь у тебя не самое лучше именование 
![image](https://user-images.githubusercontent.com/25764783/62189231-a9ff6a00-b398-11e9-8535-6a31d7a8ef07.png)
у тебя получается что элементы `.drop-down__content-wrapper` и `.drop-down__content` соседние. Хотя по именам первый элемент это оболочка для второго. Можно подумать в сторону того, чем эти элементы являются по сути, например с использованием слов select и options, как вариант
___
На первом проекте разве не обсуждали то, что на блоках БЭМ не должно быть внешней геометрии?

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
> На первом проекте разве не обсуждали то, что на блоках БЭМ не должно быть внешней геометрии?

**Comment by arkhannanov** [comment]
> На первом проекте разве не обсуждали то, что на блоках БЭМ не должно быть внешней геометрии?

Готов. Оставил только внешнюю геометрию для .headline, так как это своеобразные блок, который должен быть только посередине родительского элемента.

**Comment by Sergio-Ka** [comment]
В БЭМ нет никаких "своеобразных блоков, которые должны быть только посередение родительских блоков". В БЭМ есть блоки, у которых не должно быть влияния на окружающие элементы без исключений. И в этом задании это точно можно сделать. Если тебе надо добавить какое-то внешнее поведение, то самое время подумать об обертке, которая будет элементом того самого "родительского" блока, в котором будет лежать этот блок.

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/63709315-d788e780-c860-11e9-9ed7-b66880743a4f.png)
![image](https://user-images.githubusercontent.com/25764783/63709346-e2437c80-c860-11e9-9c92-42c1471a4695.png)
![image](https://user-images.githubusercontent.com/25764783/63709389-fb4c2d80-c860-11e9-97ec-c074971e987a.png)
![image](https://user-images.githubusercontent.com/25764783/63709424-1323b180-c861-11e9-87fc-0aeefdd20049.png)
что за segment1? что это значит у тебя?
![image](https://user-images.githubusercontent.com/25764783/63709617-79103900-c861-11e9-9f52-121570873611.png)
класс с префиксом -js в стилях использовать запрещено. Он нужен только для поиска элемента из js-файлов
![image](https://user-images.githubusercontent.com/25764783/63709733-b1177c00-c861-11e9-95c2-cd2689362bec.png)

В целом, или у меня глаз замылился, или по БЭМу всё ок(я надеюсь что 2-ое). Исправляй эти замечания, и мб Сергей еще чего добавит.

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Sergio-Ka** [comment]
Сделано частично.
1. на navigation по прежнему свойство margin висит
2. на page так же
3. segment1 надо было не удалять полностью, так как элементы без классов по стандартом оставлять нельзя, а просто тупо переименовать в segment без всяких чисел или pieSegment какой-нибудь.

**Comment by Frolikow** [comment]
а где изменения 
![image](https://user-images.githubusercontent.com/25764783/63879475-ff5d8400-c9f5-11e9-82e6-c0d882ade2d8.png)

ПОВТОРЮ: важное правило!!! 1 исправление = 1 коммит! не надо мешать несколько тасок в один комит. как проверять то потом? прикинь вот такую пачку изменений пролистать
![image](https://user-images.githubusercontent.com/25764783/63879590-3a5fb780-c9f6-11e9-9802-f305c4442f08.png)

**Comment by Sergio-Ka** [comment]
Извини, тупанул вчера. Конечно не segment или pieSegment, это же css класс, так как БЭМ работает и тут, а pie__segment. И можно создать для этого css-класса css- же правила. И в них из инлайна перенести fill, stroke (модификатором типа pie__segment.pie__segment_color_red), еще какие-то свойства, которые есть для svg в css.

**Comment by arkhannanov** [comment]
> Извини, тупанул вчера. Конечно не segment или pieSegment, это же css класс, так как БЭМ работает и тут, а pie__segment. И можно создать для этого css-класса css- же правила. И в них из инлайна перенести fill, stroke (модификатором типа pie__segment.pie__segment_color_red), еще какие-то свойства, которые есть для svg в css.

Исправлено. Нашел только эти свойства css для svg.
