### ISSUE TITLE
Очень много разнообразных оберток

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#15]
Во многих местах совсем не оправданное использование wrapper/container. **Внимательно** проверь **Весь** проект и убери лишние обертки.
Пример: 
```pug
mixin player
    .player
        .player__wrapper
            video.player__video.viewer(src="video/156181920.mp4")
            .player__controls-wrapper
                .player__controls
                    button.player__button.toggle
                    .player__progress-container
                        .player__progress
                            .player__progress_filled
                    button.player__button.fullscreen
```

зачем здесь? `.player__wrapper` `.player__controls-wrapper` `.player__progress-container`

**Comment by arkhannanov** [comment]
Убрал все ненужные обертки, также добавил клавишу Play при первоначальной загрузке. Единственное, после того как убрал обертку перестало работать совсем player__video:hover

Хотел сначала задать .player__controls display:none, а при наведении display:flex. Не работает.

**Comment by Frolikow** [comment]
тут зачем обертка нужна? 
![image](https://user-images.githubusercontent.com/25764783/61186695-77642a80-a692-11e9-8b5b-2bb55ba22aa0.png)
здесь?
![image](https://user-images.githubusercontent.com/25764783/61186706-91057200-a692-11e9-9787-a745e0d18d3c.png)
и здесь?
![image](https://user-images.githubusercontent.com/25764783/61186714-a5e20580-a692-11e9-96e5-7d5a661af5ff.png)
и тут
![image](https://user-images.githubusercontent.com/25764783/61186716-af6b6d80-a692-11e9-9a29-69d244659387.png)
и почти в каждом файле 

опять что-ли надо в каждое конкретное место указывать? я же написал тебе:

> **Внимательно** проверь **Весь** проект и убери лишние обертки.

несколько раз ведь уже об этом говорили

**Comment by arkhannanov** [comment]
1. 
![61186695-77642a80-a692-11e9-8b5b-2bb55ba22aa0](https://user-images.githubusercontent.com/41430352/61197446-ac499f00-a6dd-11e9-9ef1-7a7b1aafb8b4.png)

Тут, чтобы задать размер svg.

**Comment by Frolikow** [comment]
1. так ведь гораздо проще, написать класс для свг и ему размеры задавать, нет?
3. для drop-down почему не задать флекс блоку? какая сложность в этом?
2,4, (**и подобные места во всем проекте** ) - зачем эта обертка внутри блока? блок ведь по своей сути, почти всегда является лежит внутри элемента родительского блока. поэтому логично позиционировать этот родительский элемент, а не внутри блока создавать обертку на весь блок

**Comment by arkhannanov** [comment]
Избавился от избыточных оберток.
