### ISSUE TITLE
блок messaging 

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#17]
здесь обертка избыточна. У тебя две дивки, на внешней стили для внутренней, следовательно можно стили перенести на внутренний а внешнюю обертку удалить за ненадобностью. 
![image](https://user-images.githubusercontent.com/25764783/61588297-44a2c080-abc3-11e9-9551-41a195acda5c.png)
тоже самое
![image](https://user-images.githubusercontent.com/25764783/61588351-3e611400-abc4-11e9-81fb-ac61f6f03005.png)
что такое dark-block? зачем он? я думаю что лучше сделать один элемент типа хедера для блока, а фон задать градиентом с четкой границей. 
dark-container что значит? темный контейнер? почему решил так назвать?
![image](https://user-images.githubusercontent.com/25764783/61588399-fd1d3400-abc4-11e9-924b-980f4b795766.png)
первое сообщение, второе сообщение? можно не комментировать?)))

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
> что такое dark-block? зачем он? 

> первое сообщение, второе сообщение? можно не комментировать?)))

Артур, ну серьезно, почему такое именование? почему не по смыслу назвать эти элементы? 
Давай рассуждать так, существуют сообщения 3-х видов: входящее, исходящее и новое. На макете есть входящее и есть новое. Входящие и исходящие в текущей реализации находятся выше(но это только в текущей реализации). Элемент для нового сообщения в этой реализации находится внизу( кстати надо сделать, чтоб сообщение можно было вводить) .
В твоих классах получается верхнее и нижнее сообщение. А если мне надо чтоб пользователь вводил сообщения сверху? Классы переписывать? 
Суть: **всегда надо стараться называть по смыслу.** Не по позиции,цвету,размеру или чему-либо еще. А только по смыслу. Заглядывая в код должно быть сразу понятно что это за элемент или переменная или функция(хоть что). Для сравнения: что больше смысла содержит: `messaging__top-message` или `messaging__incoming-message `
