### ISSUE TITLE
 Блок search

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#19]
```pug
mixin search
    .search
        .search__input-container
            input.search__input(type="text", placeholder="Search")
            button.search__icon
        .search__error
```
на макете показано два состояния для поиска. Это не один блок. надо разбить и задавать модификатором(например) состояние ошибки.

**Comment by arkhannanov** [comment]
Не понял немного задачу. У меня на Search два состояния. Попробуй что-то введи в строку поиска и нажми на лупу, выскочит ошибка.

**Comment by Frolikow** [comment]
Как у тебя работает - я понял и это не правильно.
На макете есть два поля поиска, 1- поиск дефолтный, 2-поиск который не дал результатов. 
Задачи для стажеров, реализовать полноценный рабочий поиск нету. Но показать оба состояния надо. 
У тебя сейчас есть поиск(1) который если что выдает ошибку в другое поле поиска. И при этом у тебя все это один блок. 
Решение здесь простое. Отрисовываешь дважды блок поиска, но во втором случае передаешь ему параметр который будет добавлять модификатор, который в свою очередь будет менять состояние поиска.

**Comment by arkhannanov** [comment]
Исправлено. Готово.

**Comment by Frolikow** [comment]
все равно не то. У тебя сейчас получается в одном поиске ошибка невозможна.
