### ISSUE TITLE
чистка кода

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#20]
Давай еще раз почистим код. 
уже спрашивал, но еще раз спрошу) 
1)для чего здесь комменты?
2) правильно ли ты все разбил, особенно смущает "цвет" в "размерах"
3) thirdFont?? а где первый шрифт и второй?)))
![image](https://user-images.githubusercontent.com/25764783/63710217-e4a6d600-c862-11e9-824b-5841d74b7de7.png)
___
это мусор? удаляй
![image](https://user-images.githubusercontent.com/25764783/63710405-4b2bf400-c863-11e9-9875-e6608bfd6f23.png)

___
мноого мест где зачем-то пустые строки "натыканы". В js'е между методами и вообще любыми сущностями больше 1 строки нет смысла делать.
в стилях попадается и по 3 строки отступ неоправданный.
так же в стилях я давно приводил пример но что-то пошло не так...если у тебя для конкретного поля нету стилей, но не делай там отступ. Пример:
![image](https://user-images.githubusercontent.com/25764783/63710614-cab9c300-c863-11e9-9997-e95c5b5ca556.png)
![image](https://user-images.githubusercontent.com/25764783/63710620-cee5e080-c863-11e9-9d7d-feb791124bea.png)
объем код сократиться => легче читать => легче проверять => легче рефакторить

**_ВАЖНО_**
по оформлению кода, всегда пиши аккуратно.! Запомни простую вещь: твой код всегда будут читать другие разработчики. Так же как и ты всегда будешь читать чужой код. Я думаю этот момент понятен)

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
с шрифтами ты явно меня не понял. Здесь речь была о том что **опять** перечисления в именовании. Как было принято решение который из них main, а который не main?)

> 2) правильно ли ты все разбил, особенно смущает "цвет" в "размерах"

и здесь я не понял что произошло, я писал про блок констант где у тебя #4f4f4f цвет задан, ты его оставил, а те что норм были записаны - снёс

остальное вроде ок

**Comment by arkhannanov** [comment]
Готово.
