### ISSUE TITLE
video

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#23]
только щас заметил. Почему у тебя видео в репозитории??? В миксин надо передавать ссылку. В проекте хранить видео - это очень грубо

**Comment by arkhannanov** [comment]
Теперь передается адрес ресурса передается через миксин.

**Comment by Frolikow** [comment]
Странное что-то сделал. Прочитай плиз внимательнее и вдумчивее задачу. И сопоставь с тем что у тебя было, и как исправил.
