### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#3]
Сразу первым делом, что у тебя за куча `index`ов в корневом каталоге? Что они значат? `idnex1, index2,index3 .....` 
Если это страницы, то сделай папку для страниц и внутри организуй папки страниц(для каждой страницы).

**Comment by arkhannanov** [comment]
Тут не совсем понял. Нужно создать папку под каждую страницу, в нее скопировать блоки относящиеся к этой странице? Или блоки так и должны в общей папке лежать.

**Comment by arkhannanov** [comment]
Отрефакторил весь проект, на страницах слетели стили. Не могу понять в чем проблема, вроде все пути верные. Слетело автоматическое подключение стилей. Просьба подсказать.

**Comment by Frolikow** [comment]
> Тут не совсем понял. Нужно создать папку под каждую страницу, в нее скопировать блоки относящиеся к этой странице? Или блоки так и должны в общей папке лежать.

Каждая страница со своими стилями и js в отдельной папке. В эту папку можно класть только то что используется **только** этой странице. 
Блоки которые используются во всем проекте должны лежать в одном месте(сейчас blocks) и подключатся из этого места



> Отрефакторил весь проект, на страницах слетели стили. Не могу понять в чем проблема, вроде все пути верные. Слетело автоматическое подключение стилей. Просьба подсказать.

Могу ошибаться, но мне кажется на каждой странице не надо заново импортить стили. Ты ведь в index.js уже импортишь все. Попробуй убрать лишние авто-импорты, а в index.js автоматически импротить из конкретных папок, blocks,pages... И кстати срузу скажу, js-файлы тоже надо автоматически импортить

**Comment by arkhannanov** [comment]
Привет. У меня получилось подключать автоматически стили.

Есть несколько вопросов.

1) После раскидывания картинок как положено по блокам картинки слетели (ошибка 404). Использую CopyWebpackPlugin. Раньше картинки лежали в images. Не могу понять откуда система их подтягивает... Правильно ли я понимаю что сначала все картинки надо копировать CopyWebpackPlugin, а затем он их автоматически по путям подтягивает. Пробно сделал запись в конфиге  { from: PATHS.src + 'blocks/form/images', to: `blocks/form/images` }, но картинки для формы не подтянулись. Просьба подсказать.

2) Отдельные страницы я подтягиваю через новые точки входа, но прописываю все вручную. Просьба помочь автоматизировать. Пока в конфиге вот так:

module.exports = {
  entry: {
    app: './src/index.js',
    alfa: './src/pages/alfa/alfa.js',
    betta: './src/pages/betta/betta.js',
    gamma: './src/pages/gamma/gamma.js',
    sigma: './src/pages/sigma/sigma.js'
  },

и так:
new HtmlWebpackPlugin({
      filename: 'alfa.html',
      template: 'src/pages/alfa/alfa.pug',
      inject: true,
      chunks: ['alfa']
То есть вручную.

3) Не могу понять как автоматически подключить js файлы. Такой прием не работает:
function importAll(resolve) {
    resolve.keys().forEach(resolve);
  }
  
importAll(require.context('./', true, /\.(js)$/));

4) Правильно ли я понял что js файлы должны лежать в каждом блоке. Пока сделал так. Неправильно? Как правильно? Для каждой страницы js папка в корне?

5) Есть у меня 2 шрифта одинакового семейства. Обычный и тонкий. Мне сказали что черезе font-family подключать неправильно. А правильно один раз в main.scss подключить семейство, а дальше в блоках просто его модифицировать через font-weight и font-style. Сделал так, почему-то все шрифты тонкие, то есть первый шрифт из списка не подтягивается.

P.S. Пока навел кое-какой порядок.
P.P.S. Если у тебя не работаю шрифты, то скорее всего у тебя наверное что-то с распознаванием относительных путей. Пробовал ставить плагин 'resolve-url-loader'? Попробуй. У меня со шрифтами с загрузкой шрифтов все норм.

**Comment by Frolikow** [comment]
во-первых по шрифтам - ты подключаешь, например,    `	src: url('lato-black.eot');` а файл называется `Lato-Black.eot`. Исправив - у меня заработало, тоже поправь этот момент
![image](https://user-images.githubusercontent.com/25764783/59585764-72e83880-910b-11e9-9cdc-1ef4051b2dad.png)


что касается пунктов:
1) на картинках не совпдают пути и имена. Предлагаю проверить внимательно такие нюансы
![image](https://user-images.githubusercontent.com/25764783/59585606-19800980-910b-11e9-829b-dbfbd0927aef.png)
![image](https://user-images.githubusercontent.com/25764783/59585618-24d33500-910b-11e9-913f-9b030be08bb7.png)

После правки, если не поможет, то попробуй собирать прод сборку и смотреть куда у тебя картинки складываются и какие пути для картинок в стилях задаются. Может оказатся не простым процесс, но нагляден. 

___
по остальным пунктам позже посмотрю

**Comment by Frolikow** [comment]
2) Пока пусть так будет, по HtmlWebpackPlugin точно оставляй так
  А вот по точкам входа, немножко не понял, почему так сделал а не одну точку входа?

3) Если честно не пойму почему не работает require.context (он кстати у тебя не установлен, но установка не спасла). Нужно разбираться почему он не тянет скрипты

4) У тебя не сложный проект, поэтому можно хранить  в папке с блоком. Пример:
![image](https://user-images.githubusercontent.com/25764783/59657303-7ee6ff80-91ca-11e9-8cb5-5282052f1edd.png)
 
5) по поводу подключения шрифтов, могу лишь  сказать что они оба работают. На первом font-weight 400, на втором 100. Подключаются как должны. 
А то что они выглядят одинаково - это скорее всего сам шрифт такой, в стилях ты ведь можешь  font-weight менять

**Comment by arkhannanov** [comment]
1. По поводу шрифтов я перепроверил, все то же самое. Видимо просто сначала на gitHub были шрифты заглавными буквами, так как Windows не чувствителен к регистру. Перезалил шрифт на github как положено. Все равно обычный шрифт lato-black.ttf, font-weight: normal;, 	font-style: normal; не подтягивается, а подтягивается по всей видимости lato-light.ttf.

**Comment by arkhannanov** [comment]
2. C картинками теперь все норм на dev сборке.

**Comment by arkhannanov** [comment]
> Пока пусть так будет, по HtmlWebpackPlugin точно оставляй так
А вот по точкам входа, немножко не понял, почему так сделал а не одну точку входа?

Я сделал так. Так как в index.html ищется допустим скрипт от формы на четвертой странице и выскакивают ошибки. Как правильно организовать. Пока оставил так как было? Как сделать правильно?

Понимаю в React и Redux страницы переключаются динамически, один index.html и одна точка входа. Как в простом случае огранизовать?

**Comment by arkhannanov** [comment]
> У тебя не сложный проект, поэтому можно хранить в папке с блоком. Пример:

Организовал как ты написал.

**Comment by arkhannanov** [comment]
И общий вопрос по структуре... В папках page-alfa, page-betta и т.д дожны лежать компонеты от этих страниц или должно быть все плоско как организовать сейчас?

**Comment by Frolikow** [comment]
> 1. По поводу шрифтов я перепроверил, все то же самое. Видимо просто сначала на gitHub были шрифты заглавными буквами, так как Windows не чувствителен к регистру. Перезалил шрифт на github как положено. Все равно обычный шрифт lato-black.ttf, font-weight: normal;, 	font-style: normal; не подтягивается, а подтягивается по всей видимости lato-light.ttf. (Шрифт  lato-black.ttf жирнее)

я в твоем проекте меняю шрифты на любом элементе, захожу  в браузере в свойства этого элемента и вижу что стили шрифтов применяются



> 1. C картинками теперь все норм на dev сборке.

в телеграмме разобрались, надеюсь теперь норм

По структуре проекта, возник вопрос, а твои страницы которые используют элементы с макета, это что за страницы? Помниться в задании было написано что-то вроде: "сделать сайт на несколько страниц, но чтоб он не был _театром абсурда_" . А у тебя сайт что делает? или ты просто примеры из чужих работ сделал?
Разберемся с сайтом и последующие вопросы про page-alfa и т.п. должны будут пропасть

**Comment by arkhannanov** [comment]
Сделал 4-ре разных страницы с элементами из UI_Kit. Что-то неправильно? Все они со смыслом. Чужие работы я не видел, разве что примеры с картинками были...

**Comment by Frolikow** [comment]
Ну твой сайт, по факту это что? они ведь между собой вообще не связаны по смыслу. Одна страница с моего проекта списана, другие - с других) Ты задание не правильно понял.
Но, чтоб время не терять - заставлять переписывать я не буду, при этом внимательно проверю как и что ты переиспользуешь. 
**И Самое главное по твоим страницам** назови их по смыслу!) почему у тебя постоянно перечисления везде? из цифр в английский, с английского в `alfa'ы`. Но везде идет счет. Я первую страницу удалю и счет будет со второй начинаться? новый человек на проекте голову сломает почему нет страницы номер 1. Или если я 1 удалю то на остальных имя менять придется? А если 100 страниц на проекте?
ты сверстал страницы, и должен понимать что ты сверстал, что на них отображается. Придумай уже для  осмысленные названия! ))

**Comment by arkhannanov** [comment]
`Ну твой сайт, по факту это что? они ведь между собой вообще не связаны по смыслу. Одна страница с моего проекта списана, другие - с других) Ты задание не правильно понял.
Но, чтоб время не терять - заставлять переписывать я не буду, при этом внимательно проверю как и что ты переиспользуешь.
И Самое главное по твоим страницам назови их по смыслу!) почему у тебя постоянно перечисления везде? из цифр в английский, с английского в alfa'ы. Но везде идет счет. Я первую страницу удалю и счет будет со второй начинаться? новый человек на проекте голову сломает почему нет страницы номер 1. Или если я 1 удалю то на остальных имя менять придется? А если 100 страниц на проекте?
ты сверстал страницы, и должен понимать что ты сверстал, что на них отображается. Придумай уже для осмысленные названия! ))`

Готово!
