### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#4]
Не использовать перечисление в именовании. 
Начни с `idnex1, index2,index3 .....` и проверь **весь** проект на эту ошибку

**Comment by arkhannanov** [comment]
А как без перечисления? Их нужно как-то по-своему назвать, по факту это страница1, страница2, страница3 и страница4.

**Comment by arkhannanov** [comment]
Исправил везде численное перечисление.

**Comment by Frolikow** [comment]
во-первых старайся делать комиты поменьше. 1000+ изменений, очень сложно проверять. еще сложнее будет найти потом историю конкретных изменений.
во-вторых:
`численное перечисление != перечисление в именовании`

ты сделал тоже самое. перечисление в именовании никуда не делось.

Если речь идет о страницах, то имя страницы должно отображать что на странице. например: mainPage, about, contacts и т.д. Сборка у меня не собирается(шрифты не находит) - проверить не могу твои страницы.

Что касается, например, кнопок
```pug
mixin buttons
    .buttons
        .buttons__buttons-container
            .buttons__first-button-container
                button.buttons__first-button(name="button") button
            .buttons__second-button-container
                button.buttons__second-button(name="button") button
            .buttons__third-button-container
                button.buttons__third-button(name="button") button 
            .buttons__fourth-button-container
                button.buttons__fourth-button(name="button") button
```
Что ты понимаешь под словом "компонентность"? То что каждый блок можно переиспользовать? Если да, то этот миксин у тебя должен большие сомнения вызвать. 
Назови хоть один usecase где ты сможешь использовать 4 кнопки с одинаковым текстом и разными стилями) 
Сомневаюсь что такие есть) 

Как должно быть:
**Каждая** кнопка это отдельный блок. Каждую кнопку ты сможешь переисползовать столько раз сколько пожелаешь. Создай отдельный миксин для отдельной кнопки. Все стили задавай через модификаторы. Значение модификатора, также как и текст - ты будешь передавать в миксин параметрами. 
Получишь полностью независимый блок кнопки) понятно что требуется?

**Comment by arkhannanov** [comment]
Ок. Понял. Скоро выкачу. Такой вопрос, по поводу перечисления... Я просто перечислением задавал от того, что наименование ссылок допустим может меняться, а их порядок сохраняется. Это неправильно? Ок, по-максимому, постараюсь избегать перечислений...

По поводу сборки... У меня собирается, только я вопрос задал в другом ишью... У меня слетели стили когда раскидал страницы по папкам, не могу понять что не так.

**Comment by arkhannanov** [comment]
Максимально избавился от нумерования. Жду проверки.

**Comment by Frolikow** [comment]
Закрываю без проверки. Проверка будет в рамках нового ишью.
