### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#5]
Опять те же ошибки. Блоки внутри блоков, много мест по проекту.
Одно из них:
![image](https://user-images.githubusercontent.com/25764783/59172439-1cf71c00-8b72-11e9-926e-b80ec29ee549.png)
Про именование перечислением писал в  #4

**Comment by arkhannanov** [comment]
Тут исправил.

**Comment by Frolikow** [comment]
> В-третьих. Учись работать с гитом, именно с порядком работы. Привыкай делать только одну задачу в рамках одного комита. НЕ должно быть смешанных задач в одном комите. Все строго и предельно просто: 1задача=1комит.
Именование комитов. Например, ты сделал задачу и создаешь комит - всегда задумывайся что ты пишешь в комите. Это своего рода краткая история развития проекта. Комит должен пояснять что ты сделал в этом комите, но не должен быть огромным сообщением. Если с английским не очень - на учебных проектах пиши комиты на русском языке. И строго соблюдай нумерацию. Чтоб комит всегда отображался в соответствующем ишью.
В результате, получится очень прозрачная и чистая история разработки. И все задачи значительно легче будут проверятся. Следовательно, опять выигрываем во времени.

**Comment by Frolikow** [comment]
Проверить смогу позже, т.к. огромный комит, сейчас нету времени его весь изучать. Потом буду Опять смотреть в коде, что и как исправленно

**Comment by arkhannanov** [comment]
Хорошо

**Comment by arkhannanov** [comment]
Вроде все по БЭМ. Жду проверки.

**Comment by Frolikow** [comment]
Закрываю без проверки. Проверка будет в рамках нового ишью.
