### ISSUE TITLE
Миксины

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#6]
1. Не логично выглядят многие миксины, так например кнопки стрелки, зачем два миксина?)) 
Можно ведь без особого труда сделать один миксин, а направление для него передавать параметром)

2. Некоторые миксины странно называются, особенно меня смутили` side-left side-right`.
Почему не назвать их по логике? `news events`

Это же касается слайдеров? левый и правый слайдер?) а если он один на странице) почему он будет левым/правым? )  
у них ведь тоже логичное имя можно придумать) slider \ step-slider. лучше ведь

**Comment by arkhannanov** [comment]
2. Готово

**Comment by arkhannanov** [comment]
Слайдеры тоже готово.

**Comment by arkhannanov** [comment]
1. Со стрелками тоже готово.
