### ISSUE TITLE
Расхождения с макетом

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_UI#7]
![image](https://user-images.githubusercontent.com/25764783/59658759-cb343e80-91ce-11e9-9375-27c63ffce591.png)

В макете ведь 12 кнопок а не 4. это касается всего проекта. 
Твой макет должен максимальное сходство иметь с изначальным psd. 

 perfect pixel я так понимаю ты не использовал?

**Comment by arkhannanov** [comment]
Подогнал по Pixel Perfect

**Comment by arkhannanov** [comment]
Переписывал многое. Сейчас подправил.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/60235914-9bbeb980-98d3-11e9-814e-bbf6cc3cb93b.png)
![image](https://user-images.githubusercontent.com/25764783/60235926-a9743f00-98d3-11e9-8e66-26e5d5314804.png)
![image](https://user-images.githubusercontent.com/25764783/60235933-aed18980-98d3-11e9-917e-ecc70441d699.png)
![image](https://user-images.githubusercontent.com/25764783/60235959-cc065800-98d3-11e9-9057-d650b8a2e59e.png)
![image](https://user-images.githubusercontent.com/25764783/60235986-e50f0900-98d3-11e9-8c7f-103b03f788de.png)
серьезные расхождения с макетом. Макет должен выглядеть **максимально** схожим с psd. Как есть в psd так и должно быть сделано у тебя. На своем сайте располагай элементы как душе угодно, на макете - нет.

И продумай со шрифтами. Они тоже должны максимально совпадать с psd. в каждом блоке и элементе.

**Comment by arkhannanov** [comment]
Шрифты теперь работают, перебрал их немного.

**Comment by arkhannanov** [comment]
Подогнал все как мог.

**Comment by Frolikow** [comment]
Сборка опять крашиться..выдает много ошибок путей

**Comment by arkhannanov** [comment]
У меня все норм запускается. Какие ошибки?

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/60698090-f4b3d080-9f17-11e9-8d58-bfeb6860138c.png)
![image](https://user-images.githubusercontent.com/25764783/60698094-fa111b00-9f17-11e9-8ed1-d84dc5e023b9.png)
![image](https://user-images.githubusercontent.com/25764783/60698100-ff6e6580-9f17-11e9-846a-1f0407b80143.png)
![image](https://user-images.githubusercontent.com/25764783/60698109-0f864500-9f18-11e9-8ca2-8259d3d0bf12.png)
![image](https://user-images.githubusercontent.com/25764783/60698113-1745e980-9f18-11e9-97a6-3dde230e06e7.png)
![image](https://user-images.githubusercontent.com/25764783/60698118-1d3bca80-9f18-11e9-9065-e3a690067ed8.png)
![image](https://user-images.githubusercontent.com/25764783/60698122-2167e800-9f18-11e9-8cb7-bb6bd8672e34.png)
![image](https://user-images.githubusercontent.com/25764783/60698126-262c9c00-9f18-11e9-893d-a29fbfef34b9.png)
![image](https://user-images.githubusercontent.com/25764783/60698131-2fb60400-9f18-11e9-8f13-cbe133b2a4bc.png)
![image](https://user-images.githubusercontent.com/25764783/60698187-7572cc80-9f18-11e9-8455-34fb68b7bf66.png)
![image](https://user-images.githubusercontent.com/25764783/60698192-7ad01700-9f18-11e9-959c-7f3f042e8f3d.png)
![image](https://user-images.githubusercontent.com/25764783/60698197-802d6180-9f18-11e9-80b6-d0ed6bb2877f.png)

**Comment by Frolikow** [comment]
думаю одна из ошибок связана с : 
![image](https://user-images.githubusercontent.com/25764783/60698503-d7800180-9f19-11e9-9875-f297edcc751b.png)
инклюдишь и вызываешь миксин которого не существует

**Comment by arkhannanov** [comment]
Зашел под VS Code, там оказались незакоммиченные изменения. Залил их, опять все запускается. Попробуй еще раз.

**Comment by Frolikow** [comment]
Не закоммиченных изменений на 3к строк) ну да ладно) все собирается теперь) 
___
вернемся к макету)
1) на стандартных кнопках увидел только 2 состояния. В чате ведь спрашивал про состояния

2) при hover на стрелках, вся верстка ниже _прыгает_

3) на простом слайдере шкала вываливается при максимальном значении: 
![image](https://user-images.githubusercontent.com/25764783/60702395-1f5a5500-9f29-11e9-8d21-274ae3cf111b.png)

4) на пошаговом слайдере внешний вид посыпался: 
![image](https://user-images.githubusercontent.com/25764783/60702457-46b12200-9f29-11e9-9b44-17f6fa2518ba.png)
 и на пошаговом слайдере, ползунок должен перемещаться только по значения шкалы( шагами). т.е. в позиции как на скрине - ползунок не может быть.

5) на элементах формы надо:
   а) сделать что-то с инпутами. или чтоб подсказка всегда была видна, или чтоб инпут на всю ширину и укорачивался, например, при фокусе.
   б) запретить изменение размера на textarea для избежания таких вещей: 
![image](https://user-images.githubusercontent.com/25764783/60702722-e66eb000-9f29-11e9-90a0-2359889e8fa7.png)

6) в календаре не работает кнопка today. И при перелистывании месяцев, иногда сильно скачет верстка под календарем.

7) в чате проблемы с рамкой : 
![image](https://user-images.githubusercontent.com/25764783/60702997-bb389080-9f2a-11e9-909d-c30762056c8c.png)

8) при hover на видеоплеере, вся верстка  _прыгает_

**Comment by Frolikow** [comment]
9) в блоке toggles, отступы внутри переключателей не симметричны:
![image](https://user-images.githubusercontent.com/25764783/60703250-88db6300-9f2b-11e9-8c32-d1804d689ec9.png)

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Решили в переписке.

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
5. Готово

**Comment by arkhannanov** [comment]
6. Готово.

**Comment by arkhannanov** [comment]
7. Готово.

**Comment by arkhannanov** [comment]
8. Готово.

**Comment by Frolikow** [comment]
Одно осталось. Кнопка today в календаре. Нажимая на нее пролистывается до текущей даты, но выбранная дата, остается на месте

**Comment by arkhannanov** [comment]
`Одно осталось. Кнопка today в календаре. Нажимая на нее пролистывается до текущей даты, но выбранная дата, остается на месте`

Исправлено.
