### ISSUE TITLE
Проект не собирается

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_UI#8]
![image](https://user-images.githubusercontent.com/33621369/59843757-666e1500-9383-11e9-8360-afabedba0dc2.png)

**Comment by arkhannanov** [comment]
Проверь сейчас

**Comment by Sergio-Ka** [comment]
то же самое

**Comment by arkhannanov** [comment]
Привет! А какая ошибка? Все ли поставлены модули? У меня и у Егора собирается.

**Comment by arkhannanov** [comment]
Кое-как определили ошибку с Егором. Попробуй сейчас. Просто у меня она не воспроизводится.

**Comment by Sergio-Ka** [comment]
Теперь работает
