### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_UI#9]
1. Переписать всё на классах ES6.
2. Код должен соответствовать стандартам fsd. То есть по поводу var, сокращений имен переменных по типу e, d и так далее я уже говорил кажется. Но тут нужно внимательно проверить во всем проекте.
3. В такого рода вещах `d + 'px'` нужно использовать темплейт строки, то есть типа ``${d}px``. Вместо конкатенации.
4. tickbox и toggles реализовать на чистом css. Задача слишком тривиальная и часто встречающаяся, чтобы тут js использовать. Ну и потом пункт задания о том, что "все, что можно реализовать на чистом html+css, нужно на них и реализовывать" никто не отменял.

**Comment by arkhannanov** [comment]
1. Немного не понял про классы ES6. Нужно везде классы внедрить?

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Подобная запись не работает ${d}px.

**Comment by Sergio-Ka** [comment]
1. Везде.
3. ${d}px работает. Чтобы она работала корректно, ее нужно зключать в одинарные обратные кавычки, которые на букве ё

**Comment by arkhannanov** [comment]
1. То есть имеется ввиду примерно вот так?:

'use strict';

class User {
  constructor(firstName, lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }
  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
  set fullName(newValue) {
    [this.firstName, this.lastName] = newValue.split(' ');
  }

  ["test".toUpperCase()]() {
    alert("PASSED!");
  }

};

А потом сконструировать объект класса и ипользовать его методы? Правильно я понимаю? А почему так и для чего это нужно, что мы приобретаем?

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
4 и 1 Готово.

Только в одном скрипте, а именно player.js не работает addEventListener на video. Не могу понять в чем проблема, без классов все работало норм.

**Comment by arkhannanov** [comment]
4. Ошибка в player.js  нашлась, исправлена.

**Comment by Sergio-Ka** [comment]
Условно можно сказать, что сделано. Но сделано плохо. Частично уже писал некоторые замечания в других ишью. Основные претензии следующие:
Компонентность. У тебя компоненты - это черные ящики с известными интерфейсами и поведением, как они внутри работают - это вопрос другого уровня абстракций. Но этот же вопрос и диктует то как они должны быть сделаны. Возьмем slider для примера. Во-первых в него должны передаваться настройки при вызове миксинов. Это как раз и есть компонентность, ты не должен шарить по всем файлам реализаций компонента, чтобы что-то поменять. Ты лишь допустимыми параметрами описываешь возможности того что он может делать. Сейчас у тебя надо отдельно вызывать миксин слайдера, а если захочется менять его настройки - идти в файл js. Тут вообще спорно то, что он сделан руками, вид у него кривой. Одно из заданий второго проекта было научится подключать какие-нибудь библиотеки. Здесь замечательно подходит jQuery UI и ее элемент слайдер. То что сейчас - явно сделано не по pixelperfect выглядит очень криво. 
Порядок действий: Ты делаешь миксин pug в который как обычно в виде объекта передаются настройки слайдера (шаг, длина шкалы, модификаторы цветового оформления и т.д.), сам миксин в данном случае обертка с классом (или с элементом с классом) на который подключается плагин. В случае с дискретным слайдером на него может одним из элементов вешаться шкала с цифрами - которая тоже меняется динамично от параметров. Параметры записываются в data- атрибуты этой обертки, от куда потом достаются в инициализирующем методе класса слайдера в js. Здесь таким образом меняя параметры миксина при вызове не надо будет лезть еще и в js. Сам класс слайдера в инициализирующем методе вешает jquery элемент на нужный класс обертки слайдера. Здесь инкапсулируется состояние - как следствие при создании инстанса и навешивании его на несколько одинаковых элементов на странице им могут передаваться разные настройки, как следствие слайдеры на одной странице с одинаковыми классами css могут иметь разный вид. Так оно примерно для всех компонентов выглядеть должно. Компоненты которым реально требуется js для реализации - это стандартные кнопки (и только для риппл эффекта), карта, выпадающее меню, слайдеры, календарь и все. К чему было огород городить не понятно. И все это делается с помощью jQuery UI кроме карт и стандартных кнопок. На этом задании большего не требуется так как понятия об архитектуре, компонентности, об инкапсуляции состояний и прочем ООП еще здесь слабое и все это только усложняет как выполнение задания, так и проверку его. Как там в календаре, где пропасть констант идет в начале, а потом он еще и сам в js рисуется - это жесть. Оно даже если самописный компонент делать - каркас нет смысла генерировать динамически, как минимум. Константы с настройками выносятся обычно в отдельный файл и делаются подключаемым модулем. И еще куча всего, что даже смотреть нет смысла.

**Comment by arkhannanov** [comment]
1. Слайдеры сделаны на основе JQuery слайдера, данные подтягиваются из data. На странице может быть неограниченно количество слайдеров с разными data.

**Comment by arkhannanov** [comment]
2. Отредактировал календарь. Теперь только таблица грузится динамически. На самом деле не совсем понятно почему не стоит использовать динамическое создание элементов, ведь в тех же JQuery плагинах элементы создаются динамически. Разве не так?

**Comment by Sergio-Ka** [comment]
1. Проблема не в генерации динамической контента, а в том что сделано крайне посредственно. На этом задании изучается верстка и компонентный подход. Оно конечно понятно, что не сложно писать худо-бедно работающий код, а вот не говнокодить - дело не слишком простое. Программинг лучше изучать имея базу и не имея пробелов в компонентной верстке, а иначе получается каша в голове и полная дрянь в проекте. И раз уж возникают вопросы про то, зачем классы и почему с ним, то тут явно базы нет и нужно сначала теорию читать, а потом уже писать календари самописные. Тем более что как говорил уже - этого не требовалось, можно было использовать плагин.
2. Вместо этого использовать декомпозицию:
```
const DayNames = Const.DayNames;
const StartOfWeek = Const.StartOfWeek;
const Events = Const.Events;
const ClassNames = Const.ClassNames;
const Defaults = Const.Defaults;
const MonthNames = Const.MonthNames;
```
3. Лучше без грязи такого рода:
```
      if (--this._month < 0) {
        this._month += 12;
        this._year--;
      }
```
4. Писать по стандартам airBnB. Отступы должны быть в 2 пробела.
5. импорты сделать автоматом
```
import './blocks/button/button';
import './blocks/stages/stages';
import './blocks/form/form';
import './blocks/search/search';
import './blocks/location/location';
import './blocks/calendar/calendar';
import './blocks/player/player';
import './js/favicons';
import './blocks/slider/slider';
```
6. stages сделать миксином, должно передаваться количество точек, которое он будет отображать, количество точек, которое закрашено. Над реализацией подумать, но то что сейчас - не очень. Тупо менять background через js вместо навешивания модификаторов не надо. Сейчас жестко зашито 5 точек и все, а если завтра будет 25 точек, то ты в ручную будешь писать и прослушиватели навешивать? И даже если оно так делалось - зачем хардкод с указанием бэкграунда в виде строк? Как минимум можно было сделать константы под это дело.
7. Про именование переменных с использованием цифр говорил уже кажется
```
nst value1 = this.root.data('min');
        const value5 = this.root.data('max');
        const step = (this.root.data('max') - this.root.data('min')) / 4;
        const value2 = value1 + step;
        const value3 = value2 + step;
        const value4 
```

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Исправлено.

**Comment by arkhannanov** [comment]
4.

> Писать по стандартам airBnB. Отступы должны быть в 2 пробела.

Исправлено.

**Comment by arkhannanov** [comment]
5. 

> импорты сделать автоматом

Исправлено. Только на страницах выскакивают ошибки, если не находятся элементы для скрипта. Как обойти?

**Comment by arkhannanov** [comment]
5. Обошел проблему невыполняющихся скриптов на странице.

**Comment by arkhannanov** [comment]
7.

> Про именование переменных с использованием цифр говорил уже кажется

Исправлено

**Comment by arkhannanov** [comment]
6.

> stages сделать миксином, должно передаваться количество точек, которое он будет отображать, количество точек, которое закрашено. Над реализацией подумать, но то что сейчас - не очень. Тупо менять background через js вместо навешивания модификаторов не надо. Сейчас жестко зашито 5 точек и все, а если завтра будет 25 точек, то ты в ручную будешь писать и прослушиватели навешивать? И даже если оно так делалось - зачем хардкод с указанием бэкграунда в виде строк? Как минимум можно было сделать константы под это дело.

Полностью переписал Stages под требования выше.

**Comment by Sergio-Ka** [comment]
1.
```
const root = {
  jobTitleInput: document.getElementsByClassName('form-job__job-title-input')[0],
  jobTitleMessage: document.getElementsByClassName('form-job__job-title-message')[0],
  jobTitleErrorMessage: document.getElementsByClassName('form-job__job-title-error-message')[0],
  facebookInput: document.getElementsByClassName('form-job__facebook-input')[0],
  facebookMessage: document.getElementsByClassName('form-job__facebook-message')[0],
  facebookErrorMessage: document.getElementsByClassName('form-job__facebook-error-message')[0],
  twitterInput: document.getElementsByClassName('form-job__twitter-input')[0],
  twitterMessage: document.getElementsByClassName('form-job__twitter-message')[0],
  twitterErrorMessage: document.getElementsByClassName('form-job__twitter-error-message')[0],
  dribbbleInput: document.getElementsByClassName('form-job__dribbble-input')[0],
  dribbbleMessage: document.getElementsByClassName('form-job__dribbble-message')[0],
  dribbbleErrorMessage: document.getElementsByClassName('form-job__dribbble-error-message')[0],
  submitButton: document.getElementsByClassName('form-job__submit-button')[0],
  completeForm: document.getElementsByClassName('form-job__completeform')[0],
};

if (typeof root.jobTitleInput !== 'undefined') {
  new FormJob(root);
}
```
почему нельзя было передавать элемент form-job и для него создавать инстанс, а уже в нем, внутри скрипта искать все эти элементы в каком-нибудь методе?
Вообще этот вопрос актуален для всех твоих js. Такое впечатление, что ты создаешь класс ради класса. Класс нужен, чтобы инкапсулировать состояние и сложность, о чем я говорил уже. А у тебя класс создается и еще поверх какие-то действия вне класса происходят - поиск по DOM, какие-то константы объявляются. Ты должен передавать один корневой элемент в класс при создании (можно при циклическом переборе, чтобы захватить все элементы с одинаковым классом, которые есть в классе, типа например несколько слайдеров на странице), а далее уже в классе, в этом корневом элементе искать элементы нужные для того чтобы с ним что-то делать, искать элемент с data- атрибутами, из которых извлекать параметры для настройки того или иного компонента.
2. в файле location.js вообще нет никаких классов.
3. использовать нативные методы массивов, в данном случае forEach подходит неплохо, или each если jquery. И вообще при работе с массивами и объектами стараться использовать нативные методы, это есть в стандартах. Так же не плохо бы писать однотипно, а то где-то выборка в dom идет с помощью jquery, где-то с помощью нативных методов js.
```
const root = document.getElementsByClassName('search');

for (let i = 0; i < root.length; i += 1) {
  new Search(root[i]);
}
```

**Comment by Frolikow** [comment]
Дополню.
1) Все классы элементов которые ищешь в js, должны быть с префиксом `js-`. 
![image](https://user-images.githubusercontent.com/25764783/62194937-0ff1ee80-b3a5-11e9-9995-fcffa9794d54.png)
2) Проблемы с именованием. Не используй сокращения. ЛУчше вообще никогда) пиши все имена переменных, функций и т.д. целыми словами. Представь проект на 1000+ файлов, несколько человек работают над разными участками, один разработчик напишет `keyNav` а другой будет использовать `navigationKeys`. И потом подключается третий и ему надо найти все места где используются эти кнопки навигации...Ему будет больно. Поэтому лучше когда весь код даже от разных разработчиков пишется в едином стиле(в данном случае- без сокращений)
3) может быть стоит задавать иконку на кнопке с помощью модификатора?
![image](https://user-images.githubusercontent.com/25764783/62195711-c2768100-b3a6-11e9-8d6b-715d5d20dcf4.png)
4) что это? тернарный оператор который лежит в переменной ` метод`?
![image](https://user-images.githubusercontent.com/25764783/62195771-e1751300-b3a6-11e9-81d3-549c6df040bd.png)
вот подсказка даже, тебя не смущает что строка в переменной `метод`. Лучше такого именования избегать. Оно не очевидно, и даже наоборот запутывает. 
5) имена обработчиков событий, должны четко отображать что за действие они отображают и 

> именоваться по шаблону  handle[ElementName]EventName. Обоснование: именуя колбэки по такому шаблону мы не будем тратить время на придумывание имени и всегда (в связке с пунктами соглашений из подраздела БЭМ) можем понять предназначение колбэка лишь посмотрев на его имя. Примечание: в случаях, когда тело обработчика используется где-то ещё, то его следует выносить в отдельную функцию, чтобы не использовать это имя. Т.е., например, обработчик handleButtonClick выводящий список итемов может только передаваться в пропс onClick БЭМ-элемента "button"; если требуется вывести список в каких-то других случаях, то следует определить метод showItems и перенести туда тело метода handleButtonClick, а в самом handleButtonClick вызывать только showItems. (стандарты)

6) не понятно зачем так много методов в конструкторе? Почему не вынести в один метод и там вызывать всю эту пачку?
![image](https://user-images.githubusercontent.com/25764783/62196636-9956f000-b3a8-11e9-8c15-0b682480252e.png)

7) это место выглядит очень захардкоженым...зачем вообще js'у знать что за строка где должна лежать? и кажется тут опять стоит напомнить про компонентную верстку(выпадющий список не миксином сделан)
![image](https://user-images.githubusercontent.com/25764783/62197049-59dcd380-b3a9-11e9-85a3-a8deb986353c.png)

 8) комментариев в коде быть не должно , это мусор. Копируя с интернета не забывай приводить код к стандартам
![image](https://user-images.githubusercontent.com/25764783/62197300-cb1c8680-b3a9-11e9-8286-115e1dcb5fc7.png)

9) такого слова нету 
![image](https://user-images.githubusercontent.com/25764783/62198106-3ca90480-b3ab-11e9-8748-2b70e10fbdb0.png)

почти все ошибки не единичные и встречаются в других местах. исправляй внимательно

**Comment by arkhannanov** [comment]
1. Исправлено.

**Comment by arkhannanov** [comment]
2. Как же нет классов? Вот эта строчка.

const myMap = new ymaps.Map('map', {...

**Comment by arkhannanov** [comment]
3. В обычном js сделал цикл перебора. В JQuery оставил $sliders.each

**Comment by arkhannanov** [comment]
1. Готово, добавлены префиксы js

**Comment by arkhannanov** [comment]
2. Избавился от сокращений

**Comment by arkhannanov** [comment]
3. Так очень коротко, компактно. А то так модификатор со стилем нужно один добавить, другой удалить.

**Comment by arkhannanov** [comment]
4. method заменил на methodTitle. Теперь более понятно.

**Comment by arkhannanov** [comment]
5. Исправлены имена обработчиков событий.

**Comment by arkhannanov** [comment]
6. Убраны избыточные методу из конструкторов.

**Comment by arkhannanov** [comment]
7. Выполнено в рамках ишью #16

**Comment by arkhannanov** [comment]
8. Удалены ненужные комментарии.

**Comment by arkhannanov** [comment]
9. Исправлено diametr на diameter

**Comment by Sergio-Ka** [comment]
1. Где-то в фалах js используется метод forEach где-то простой цикл for, где-то each из jquery. Про то что нужно использовать нативные методы и про то чтобы стараться писать единообразно уже писал в прошлом своем комментарии. Пока можно констатировать, что это не выполнено. В кнопках инстансы создаются пребором элементов DOM с помощью forEach далее просто for используется.
2. Вот здесь что-то вообще плохо (это для примера, вообще не только здесь это). Получается мы передаем корневой элемент в класс, его пишем в поле класса, потом из него берем элементы (при чем очень странно, тупо по индексам, а если завтра  надо будет поменять элементы местами, мы сломаем в этих дебрях индексов ноги) и записываем их в то же поле класса в котором лежит корневой элемент, только под другими именами? А потом к ним обращаемся и каждый раз вынуждены писать слово root?
{
    this.root.jobTitleInput = this.root.children[1].children[0];
    this.root.jobTitleMessage = this.root.children[1].children[1];
    this.root.jobTitleErrorMessage = this.root.children[2];
    this.root.facebookInput = this.root.children[3].children[0];
    this.root.facebookMessage = this.root.children[3].children[1];
    this.root.facebookErrorMessage = this.root.children[4];
    this.root.twitterInput = this.root.children[5].children[0];
    this.root.twitterMessage = this.root.children[5].children[1];
    this.root.twitterErrorMessage = this.root.children[6];
    this.root.dribbbleInput = this.root.children[7].children[0];
    this.root.dribbbleMessage = this.root.children[7].children[1];
    this.root.dribbbleErrorMessage = this.root.children[8];
    this.root.submitButton = this.root.children[10].children[0];
    this.root.completeForm = this.root.children[0];
  }
3. в файле location.js по прежнему нет классов.

**Comment by Frolikow** [comment]
По моим замечаниям:
1.) префикс добавил. Но как-то бездумно это сделал. что теперь за стили для классов с префиксом js-? Ты понимаешь назначение этого префикса, для чего он нужен?
2.) ок, вроде больше не увидел сокращений ненужных
3.) пока оставим как есть
4.) мне не стало понятнее если честно. Скажи вкратце, как ты переводишь это словосочетание и какой ты видишь смысл у этой переменной
5.) Много мест где не правильно сделал. например: 
![image](https://user-images.githubusercontent.com/25764783/62649609-56d07d00-b97f-11e9-8038-62785329f9f1.png)
элемент search или searchInput?
тоже самое
![image](https://user-images.githubusercontent.com/25764783/62649677-7667a580-b97f-11e9-9795-b8afaf6cebb8.png)
здесь ведь на window обработчик вешаешь
![image](https://user-images.githubusercontent.com/25764783/62649758-99925500-b97f-11e9-865c-f2e3198bef7a.png)
это **_не все_** что надо исправить, проверь весь проект
8.)
>  Удалены ненужные комментарии.
 
остались нужные??
![image](https://user-images.githubusercontent.com/25764783/62650072-3f45c400-b980-11e9-9524-abddc0652ccf.png)

![image](https://user-images.githubusercontent.com/25764783/62650089-453ba500-b980-11e9-9433-93f1948baa07.png)

![image](https://user-images.githubusercontent.com/25764783/62650143-64d2cd80-b980-11e9-8f36-ca033b5df9bf.png)
**_Весь_** проект проверь

**Comment by arkhannanov** [comment]
> 1. Где-то в фалах js используется метод forEach где-то простой цикл for, где-то each из jquery. Про то что нужно использовать нативные методы и про то чтобы стараться писать единообразно уже писал в прошлом своем комментарии. Пока можно констатировать, что это не выполнено. Например, в кнопках инстансы создаются пребором элементов DOM с помощью forEach далее просто for используется.

Использовал везде цикл for, forEach для календаря почему-то не работал.

**Comment by arkhannanov** [comment]
> 2. Вот здесь что-то вообще плохо (это для примера, вообще не только здесь это). Получается мы передаем корневой элемент в класс, его пишем в поле класса, потом из него берем элементы (при чем очень странно, тупо по индексам, а если завтра надо будет поменять элементы местами, мы сломаем в этих дебрях индексов ноги) и записываем их в то же поле класса в котором лежит корневой элемент, только под другими именами? А потом к ним обращаемся и каждый раз вынуждены писать слово root?

Везде где нужно исправил.

**Comment by arkhannanov** [comment]
> 3. В файле location.js по прежнему нет классов.
Добавил класс Location

**Comment by arkhannanov** [comment]
1.) Исправлено.

**Comment by arkhannanov** [comment]
> 4.) мне не стало понятнее если честно. Скажи вкратце, как ты переводишь это словосочетание и какой ты видишь смысл у этой переменной

handleTogglePlayClick() {
    const methodTitle = this.video.paused ? 'play' : 'pause';
    this.video[methodTitle]();
  }

У this.video есть методы, в зависимости от того стоит пауза или плей выбирается(меняется метод this.video) и дописываются (), чтобы вызвать этот метод. Поэтому и константа называется methodTitle - название метода.

**Comment by arkhannanov** [comment]
> 5.) Много мест где не правильно сделал. например:

Исправлены наименования хендлеров.

**Comment by arkhannanov** [comment]
8.) Удалены ненужные комментарии.

**Comment by Sergio-Ka** [comment]
1. Простой метод for используется вообще для любого перебора, я говорил об использовании нативных методов массивов, даже предлагал использовать forEach в первом своем замечании на эту тему.
2. Магические числа 625 и 80 не понятно что означающие. Выносятся в константы как минимум. У констант - осмысленные имена. Должны быть.
![image](https://user-images.githubusercontent.com/33621369/62997630-28790300-be93-11e9-85f7-c6c2d739059e.png)
3. Я все еще не понимаю, почему какая-то работа, относящаяся по логике к классу делается снаружи класса, а не инкапсулирована в него? Снаружи только поиск по DOM и передача найденных элементов в качестве параметров при создании инстанса.
const root = document.getElementsByClassName('js-calendar__item');

for (let i = 0; i < root.length; i += 1) {
  window.onload = () => {
    if (root[i] != null) {
      const today = new Date();

      const calendar = new Calendar(root[i], {
        minDate: new Date(
          today.getFullYear(),
          today.getMonth(),
          today.getDate()
        ),
        maxDate: new Date(
          today.getFullYear() + 1,
          today.getMonth(),
          today.getDate()
        ),
      });

      root[i].addEventListener(Events.DATE_SELECTED, (event) => {
        calendar.setDate(event.detail.date);
      });
    }
  };
};
4.То же самое про location. Не пойму зачем там что-то болтается снаружи класса в отдельном файле и почему оно не может быть инкапсулировано?

**Comment by Frolikow** [comment]
> > 4.) мне не стало понятнее если честно. Скажи вкратце, как ты переводишь это словосочетание и какой ты видишь смысл у этой переменной
> 
> handleTogglePlayClick() {
> const methodTitle = this.video.paused ? 'play' : 'pause';
> this.videomethodTitle;
> }
> 
> У this.video есть методы, в зависимости от того стоит пауза или плей выбирается(меняется метод this.video) и дописываются (), чтобы вызвать этот метод. Поэтому и константа называется methodTitle - название метода.

Это, на мой взгляд, настолько неудачное именование, что здесь лучше подумать как вообще избавиться от этой переменной. 
У меня на ум пришел  такой вариант, мб у тебя что-то элегантнее получиться
![image](https://user-images.githubusercontent.com/25764783/63012474-8407b880-beb4-11e9-968e-af43832a92ce.png)

**Comment by arkhannanov** [comment]
1. Готово. Используются нативные методы.

**Comment by arkhannanov** [comment]
2. Избавился от магических чисел.

**Comment by arkhannanov** [comment]
> 3. Я все еще не понимаю, почему какая-то работа, относящаяся по логике к классу делается снаружи класса, а не инкапсулирована в него? Снаружи только поиск по DOM и передача найденных элементов в качестве параметров при создании инстанса.
const root = document.getElementsByClassName('js-calendar__item');

Отредактирован немного. Никакой логики не совершается, а создается экземпляр класса через new с параметрами (root, {minDate, maxDate, selectedDate}). Передается минимальная Дата, максимальная Дата и устанавливается Дата на экземпляр класса.

**Comment by arkhannanov** [comment]
4.То же самое про location. Не пойму зачем там что-то болтается снаружи класса в отдельном файле и почему оно не может быть инкапсулировано?

Готово.

**Comment by arkhannanov** [comment]
> Это, на мой взгляд, настолько неудачное именование, что здесь лучше подумать как вообще избавиться от этой переменной.
У меня на ум пришел такой вариант, мб у тебя что-то элегантнее получиться

**Comment by Frolikow** [comment]
> > Это, на мой взгляд, настолько неудачное именование, что здесь лучше подумать как вообще избавиться от этой переменной.
> > У меня на ум пришел такой вариант, мб у тебя что-то элегантнее получиться
> 
> Готово.

интересно получается) я тебе написал решение из трех строк и предложил придумать элегантнее) а тебя получился мой вариант но на 4 строки)

**Comment by arkhannanov** [comment]
> Это, на мой взгляд, настолько неудачное именование, что здесь лучше подумать как вообще избавиться от этой переменной.
У меня на ум пришел такой вариант, мб у тебя что-то элегантнее получиться

Готово.

интересно получается) я тебе написал решение из трех строк и предложил придумать элегантнее) а тебя получился мой вариант но на 4 строки)

Ой, да, сорри. Обратил внимание только на проблемную строку, которая обсуждалась.

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
По мне js норм. Ждем вердикт владельца ишью)

**Comment by Sergio-Ka** [comment]
Посмотри публичные - приватные методы во всех классах во всех js-ках. А то какие-то у тебя приватные, а какие-то публичные судя по обозначению, хотя по логике и виду - частные. Напоминаю, что частные методы начинаются со знака подчеркивания "_". Приватные (частные) методы это те, которые используются для внутренних нужд класса и снаружи класса не вызываются. После этого можешь самостоятельно закрыть это замечание.

**Comment by arkhannanov** [comment]
Готово.
